securitySchemes:
  cookieAuth:
    type: apiKey
    in: cookie
    name: token
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
  csrfHeader:
    type: apiKey
    in: header
    name: x-csrf-token
