openapi: 3.0.3
info:
  title: La Margarita API
  version: 1.0.0
  description: API de La Margarita. Textos descriptivos en español.
  contact:
    name: Soporte La Margarita
    email: soporte@lamargarita.com
servers:
  - url: http://localhost:3000
    description: Desarrollo local
  - url: https://api.lamargarita.com
    description: Producción
tags:
  - name: Auth
    description: Autenticación y sesiones
  - name: Users
    description: Gestión de usuarios
  - name: Products
    description: Productos
  - name: Carts
    description: Carritos
  - name: Reservations
    description: Reservas
  - name: Reviews
    description: Opiniones
  - name: Images
    description: Imágenes
  - name: Contacts
    description: Contacto
  - name: Lodgings
    description: Alojamientos
  - name: Tickets
    description: Tickets de compra
